FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src
COPY . .

RUN dotnet restore "./Fakes/Fakes.csproj"
RUN dotnet publish "./Fakes/Fakes.csproj" -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app ./

EXPOSE 5678

ENTRYPOINT [ "dotnet", "Fakes.dll" ]
